version: '3'
services:
  database:
    build:
      dockerfile: Dockerfile
      context: ./dbmongod
  web:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - "5000:5000"


